language: node_js
node_js:
  - "stable"
install:
  # get the reporter for Code Climate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
cache:
  directories:
    - "node_modules"
script:
  - npm run build
  - npm run coveralls
after_script:
  - |
    # Upload coverage to coveralls
    npm install --save-dev coveralls@2.10.0
    coveralls < ./coverage/lcov.info
env:
  # just an example, configure it in Travis to hide it, OK...?
  - CC_TEST_REPORTER_ID=ABC123