env:
  global:
    - CC_TEST_REPORTER_ID=76ded8beb1f1781866ae0e5c4cea77de3c309fa96a12035cdd0a13c0020adfa8
language: node_js
node_js:
  - "stable"
addons:
  code_climate:
    repo_token: TweeikAFGpg0c6Ds9lcJCc1z4R9CxgaK8
cache:
  directories:
    - "node_modules"
before_script:
  - npm install --save-dev coveralls@2.10.0
  - npm install codeclimate-test-reporter istanbul -g
script:
  - npm run build
  - npm run coveralls
after_script:
  - coveralls < ./coverage/lcov.info
  - codeclimate-test-reporter < ./coverage/lcov.info
