language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
script:
  - npm run build
  - npm run coveralls
after_script:
  - |
    # Upload coverage to coveralls
    npm install --save-dev coveralls@2.10.0
    coveralls < ./coverage/lcov.info
    set CODECLIMATE_REPO_TOKEN=76ded8beb1f1781866ae0e5c4cea77de3c309fa96a12035cdd0a13c0020adfa8
    codeclimate < build\reports\coverage\report-lcov\lcov.info