env:
  global:
    - CC_TEST_REPORTER_ID=ABC123
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run build
  - npm run coveralls
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - |
    # Upload coverage to coveralls
    npm install --save-dev coveralls@2.10.0
    coveralls < ./coverage/lcov.info