env:
  global:
    - CC_TEST_REPORTER_ID=20e5405a8bc9cc392cac6e0bae95b2e7e38273e94c5dff726851c0380c3142bc
language: node_js
node_js:
  - "stable"
addons:
  code_climate:
    repo_token: TweeikAFGpg0c6Ds9lcJCc1z4R9CxgaK8
cache:
  directories:
    - "node_modules"
before_script:
  - npm install --save-dev coveralls
  - npm install codeclimate-test-reporter istanbul -g
script:
  - npm run coveralls
after_script:
  - coveralls < ./coverage/lcov.info
  - codeclimate-test-reporter < ./coverage/lcov.info
